"""Generation of the SIMION workbench Lua program ("harness").

SIMION only executes a workbench program that sits next to the .iob and shares
its basename -- it cannot be supplied via `--lua @file` (SIMION rejects that
with "You attempted to execute a special workbench program"). So controlling
electrode voltages or recording per-ion results requires writing that file.

The harness records via `segment.other_actions` rather than `segment.terminate`
because terminate only fires for ions that strike an electrode; ions leaving
the array boundary never trigger it and would silently vanish from results.
"""

from pathlib import Path
from typing import Optional

from .core import backup_file

SENTINEL = "-- SIMION-MCP-GENERATED-HARNESS v2"

CSV_COLUMNS = [
    "ion_n", "tof_usec", "x_mm", "y_mm", "z_mm",
    "vx", "vy", "vz", "ke_ev", "mass_amu", "charge",
    "hit_electrode", "initial_ke_ev",
]


def build_harness(electrodes: Optional[list[int]] = None) -> str:
    """Return Lua source for a workbench program.

    electrodes: electrode numbers whose voltage should be driven from the
        MCP_V<n> globals. Electrodes omitted here are left untouched so the
        workbench's own stored potentials still apply.
    """
    electrodes = sorted(set(electrodes or []))

    adjust_lines = []
    for n in electrodes:
        adjust_lines.append(
            f"  if MCP_V{n} ~= nil then adj_elect{n:02d} = MCP_V{n} end"
        )
    adjust_body = "\n".join(adjust_lines) if adjust_lines else "  -- no electrodes driven"

    header = ",".join(CSV_COLUMNS)

    return f"""{SENTINEL}
-- Auto-generated by simion-mcp. Safe to delete; it will be regenerated.
simion.workbench_program()

MCP_CSV = MCP_CSV or "simion_mcp_result.csv"

local last = {{}}      -- ion_number -> latest recorded state
local order = {{}}     -- preserves first-seen ion order
local splatted = {{}}  -- ion_number -> true if it struck an electrode
local initial_ke = {{}}

local function ke_now()
  local speed = math.sqrt(ion_vx_mm^2 + ion_vy_mm^2 + ion_vz_mm^2)
  return simion.speed_to_ke(speed, ion_mass)
end

function segment.fast_adjust()
{adjust_body}
end

-- Fires every time step for every ion, so it sees ions that leave the array
-- as well as ions that splat on an electrode.
function segment.other_actions()
  local n = ion_number
  if last[n] == nil then
    order[#order+1] = n
    initial_ke[n] = ke_now()
  end
  last[n] = {{
    ion_time_of_flight, ion_px_mm, ion_py_mm, ion_pz_mm,
    ion_vx_mm, ion_vy_mm, ion_vz_mm, ke_now(), ion_mass, ion_charge,
  }}
end

-- Only called for electrode collisions; used purely to flag them.
function segment.terminate()
  splatted[ion_number] = true
end

function segment.terminate_run()
  local fh, err = io.open(MCP_CSV, "w")
  if not fh then
    print("error,MCP harness could not open " .. tostring(MCP_CSV) .. ": " .. tostring(err))
    return
  end
  fh:write("{header}\\n")
  for _, n in ipairs(order) do
    local r = last[n]
    fh:write(string.format(
      "%d,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%.10g,%d,%.10g\\n",
      n, r[1], r[2], r[3], r[4], r[5], r[6], r[7], r[8], r[9], r[10],
      splatted[n] and 1 or 0, initial_ke[n] or 0))
  end
  fh:close()
  print("status,MCP harness wrote " .. #order .. " ion records to " .. MCP_CSV)
end
"""


def is_generated(path: Path) -> bool:
    """True if `path` is a harness this tool wrote (safe to replace silently)."""
    try:
        with path.open("r", errors="replace") as fh:
            return SENTINEL.split(" v")[0] in fh.read(400)
    except OSError:
        return False


def install_harness(
    iob_path: Path,
    electrodes: Optional[list[int]] = None,
    allow_overwrite: bool = False,
) -> dict:
    """Write the harness to <workbench>.lua beside the .iob.

    Refuses to clobber a hand-written workbench program unless allow_overwrite
    is set, and always backs up whatever it replaces.
    """
    iob_path = Path(iob_path).resolve()
    lua_path = iob_path.with_suffix(".lua")

    backup = None
    if lua_path.exists():
        if not is_generated(lua_path):
            if not allow_overwrite:
                return {
                    "ok": False,
                    "error": (
                        f"{lua_path.name} already exists and was not generated by "
                        "simion-mcp. It is probably the workbench's own program. "
                        "Pass allow_overwrite=true to replace it (a .bak copy is kept), "
                        "or run in a copied workspace via simion_prepare_workspace."
                    ),
                    "existing_lua": str(lua_path),
                }
            backup = backup_file(lua_path)

    lua_path.write_text(build_harness(electrodes), encoding="utf-8")
    return {"ok": True, "lua_path": str(lua_path), "backup": backup}
